config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :line_items
  resources :carts
  resources :instruments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/instrument.rb
class Instrument < ApplicationRecord
    before_destroy :not_referenced_by_any_line_item 

    mount_uploader :image, ImageUploader # carrierwave support for our image column 
    belongs_to :user, optional: true 

    validates :title, :brand, :price, :model, presence: true 
    validates :description, length: {maximum: 1000, too_long: "%{count} characters is the maximum allowed"}
    validates :title, length: { maximum: 140, too_long: "%{count} characters is the maximum allowed" }
    validates :price, numericality: { only_integer: true }, length: { maximum: 7 }

    BRAND = %w{ Fender Gibson Epiphone ESP Martin Dean Taylor Jackson PRS  Ibanez Charvel Washburn } # creates an array of words
    FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
    CONDITION = %w{ New Excellent Mint Used Fair Poor }

    has_many :linet_items 

    private 

    def not_referenced_by_any_line_item 
        unless line_items.empty? 
            errors.add(:base, 'Line items present')
            throw :abort 
        end
    end
    

end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /instruments or /instruments.json
  def index
    @instruments = Instrument.all
  end

  # GET /instruments/1 or /instruments/1.json
  def show
  end

  # GET /instruments/new
  def new
    @instrument = current_user.instruments.build
  end

  # GET /instruments/1/edit
  def edit
  end

  # POST /instruments or /instruments.json
  def create
    @instrument = current_user.instruments.build(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to instrument_url(@instrument), notice: "Instrument was successfully created." }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1 or /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to instrument_url(@instrument), notice: "Instrument was successfully updated." }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1 or /instruments/1.json
  def destroy
    @instrument.destroy

    respond_to do |format|
      format.html { redirect_to instruments_url, notice: "Instrument was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def instrument_params
      params.require(:instrument).permit(:brand, :model, :description, :condition, :finish, :title, :price)
    end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
    def instrument_author(instrument)
        user_signed_in? current_user.id == instrument.user_id
    end
end

app/views/instruments/_form.html.erb
<%= form_with(model: instrument) do |form| %>
  <% if instrument.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
        <% instrument.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :condition, style: "display: block" %>
    <%= form.text_field :condition %>
  </div>

  <div>
    <%= form.label :finish, style: "display: block" %>
    <%= form.text_field :finish %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/instruments/_instrument.html.erb
<div id="<%= dom_id instrument %>">
  <p>
    <strong>Brand:</strong>
    <%= instrument.brand %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= instrument.model %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= instrument.description %>
  </p>

  <p>
    <strong>Condition:</strong>
    <%= instrument.condition %>
  </p>

  <p>
    <strong>Finish:</strong>
    <%= instrument.finish %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= instrument.title %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= instrument.price %>
  </p>

</div>

app/views/instruments/edit.html.erb
<h1>Editing instrument</h1>

<%= render "form", instrument: @instrument %>

<br>

<div>
  <%= link_to "Show this instrument", @instrument %> |
  <%= link_to "Back to instruments", instruments_path %>
</div>

app/views/instruments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Instruments</h1>

<div id="instruments">
  <% @instruments.each do |instrument| %>
    <%= render instrument %>
    <p>
      <%= link_to "Show this instrument", instrument %>
    </p>
  <% end %>
</div>

<%= link_to "New instrument", new_instrument_path %>

app/views/instruments/new.html.erb
<h1>New instrument</h1>

<%= render "form", instrument: @instrument %>

<br>

<div>
  <%= link_to "Back to instruments", instruments_path %>
</div>

app/views/instruments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @instrument %>

<div>
  <%= link_to "Edit this instrument", edit_instrument_path(@instrument) %> |
  <%= link_to "Back to instruments", instruments_path %>

  <%= button_to "Destroy this instrument", @instrument, method: :delete %>
</div>